### ISSUE TITLE
Add logo to aws

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-versium#1]
Can you please add this @justinwinslow?

![versium-logo-top](https://cloud.githubusercontent.com/assets/3402403/9802497/2f29f754-57e0-11e5-8ccb-6c7ff727adb2.png)

**Comment by justinwinslow** [comment]
https://s3.amazonaws.com/integration-logos/versium.png

**Comment by ros3bud** [comment]
Thanks!
